spring.application.name=api
upload.directory=$projectDir/uploads
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework

server.port=${PORT:8080}

# Configuration BDD (sera surcharg�e par les variables d'environnement Docker)
#spring.datasource.url=jdbc:postgresql://localhost:5432/tripizdatabase
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tripizdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tripiz}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tripiz123}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


#Configuration BDD
# spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:39238/railway
# spring.datasource.username=postgres
# spring.datasource.password=jNnSkEoBgTBaaYVAIcSHlsQPgnHcKFJS

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Informations notchpay
notchpay.key.public =pk_test.jyxmUJcFVBLFaSCMQs2EE0c5w79xY7txNE8ikxAogBjOnPSu0DUXLye9aa8fNbxiSPWeHVoXShTpCHQ3HN6xFpvyfbNAXi4PymTq1MVHg49EpXQk9sUNyJ0af1XqC
notchpay.key.private = sk_test.bLgOutucdzv6Xzdh0fUizAA1f3JOG4rdFXV285SHNtERCwzEhNdjBlpPSWSie4jsoZm9WLlTdwAjUqwBMR4eRan97wJWDstg3wVG2EMSEL3R4lqPYn3zKzaBWCR3x



# Keycloak OIDC
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/tripiz}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/tripiz/protocol/openid-connect/certs}
# Keycloak Admin API
keycloak.auth-server-url=${KEYCLOAK_AUTH_URL:https://keycloak-production-53a7.up.railway.app}
keycloak.realm=${KEYCLOAK_REALM:tripiz}
keycloak.admin-client-id=admin-cli
keycloak.admin-client-secret=${KEYCLOAK_ADMIN_SECRET:fWPoBGrACayTYGD3rDnRBzf3LlTs8D8z}